import type { Appointment, Service, Stylist, Tender } from "./types";
import { getDateISO } from "./utils";

export const SERVICES: Service[] = [
  {
    id: "s1",
    name: { az: "Klassik saç kəsimi", ru: "Классическая стрижка" },
    category: "haircut",
    durationMin: 45,
    price: 25,
  },
  {
    id: "s2",
    name: { az: "Modern fade kəsim", ru: "Современная стрижка фейд" },
    category: "haircut",
    durationMin: 60,
    price: 35,
  },
  {
    id: "s3",
    name: { az: "Uşaq saç kəsimi", ru: "Детская стрижка" },
    category: "haircut",
    durationMin: 30,
    price: 18,
  },
  {
    id: "s4",
    name: { az: "Saqqal düzəltmə", ru: "Коррекция бороды" },
    category: "beard",
    durationMin: 25,
    price: 15,
  },
  {
    id: "s5",
    name: { az: "Premium saqqal forması", ru: "Премиум моделирование бороды" },
    category: "beard",
    durationMin: 40,
    price: 28,
  },
  {
    id: "s6",
    name: { az: "Tam saç boyama", ru: "Полное окрашивание волос" },
    category: "coloring",
    durationMin: 120,
    price: 90,
  },
  {
    id: "s7",
    name: { az: "Melir və balayaj", ru: "Мелирование и балаяж" },
    category: "coloring",
    durationMin: 150,
    price: 120,
  },
  {
    id: "s8",
    name: { az: "Fön və stayl", ru: "Сушка феном и укладка" },
    category: "styling",
    durationMin: 45,
    price: 30,
  },
  {
    id: "s9",
    name: { az: "Toy saç düzümü", ru: "Свадебная причёска" },
    category: "styling",
    durationMin: 90,
    price: 75,
  },
  {
    id: "s10",
    name: { az: "Keratin düzləşdirmə", ru: "Кератиновое выпрямление" },
    category: "styling",
    durationMin: 180,
    price: 180,
  },
  // Event-tier services
  {
    id: "s11",
    name: { az: "Toy çəkilişi (8 saat)", ru: "Свадебная съёмка (8 часов)" },
    category: "shoot",
    durationMin: 480,
    price: 800,
  },
  {
    id: "s12",
    name: { az: "Lovestory çəkiliş", ru: "Lovestory-съёмка" },
    category: "shoot",
    durationMin: 180,
    price: 220,
  },
  {
    id: "s13",
    name: { az: "Ailə çəkilişi", ru: "Семейная съёмка" },
    category: "shoot",
    durationMin: 90,
    price: 150,
  },
  {
    id: "s14",
    name: { az: "DJ-set (4 saat)", ru: "DJ-сет (4 часа)" },
    category: "djset",
    durationMin: 240,
    price: 400,
  },
  {
    id: "s15",
    name: { az: "Korporativ DJ-set", ru: "Корпоративный DJ-сет" },
    category: "djset",
    durationMin: 300,
    price: 550,
  },
  {
    id: "s16",
    name: { az: "Toy banketi (şəxs üçün)", ru: "Свадебный банкет (на персону)" },
    category: "banquet",
    durationMin: 360,
    price: 75,
  },
  {
    id: "s17",
    name: { az: "Premium banket menyu", ru: "Премиум банкетное меню" },
    category: "banquet",
    durationMin: 360,
    price: 120,
  },
  {
    id: "s18",
    name: { az: "Toy aparıcısı (axşam)", ru: "Ведущий свадьбы (вечер)" },
    category: "host",
    durationMin: 360,
    price: 500,
  },
];

export const STYLISTS: Stylist[] = [
  {
    id: "u1",
    name: "Elvin Məmmədov",
    bio: {
      az: "10 ildən artıq təcrübəli kişi ustası. Klassik və müasir kəsimlərdə ixtisaslaşıb.",
      ru: "Мужской мастер с опытом более 10 лет. Специализируется на классических и современных стрижках.",
    },
    rating: 4.9,
    reviewsCount: 234,
    specialties: ["haircut", "beard"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s4", "s5"],
    workingHours: { start: "09:00", end: "19:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: { az: "Bakı", ru: "Баку" },
    kind: "barber",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 8,
    experienceYears: 10,
    district: { az: "Bakı, Nəsimi", ru: "Баку, Насими" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/elvin1/600/450",
      "https://picsum.photos/seed/elvin2/600/450",
      "https://picsum.photos/seed/elvin3/600/450",
      "https://picsum.photos/seed/elvin4/600/450",
    ],
  },
  {
    id: "u2",
    name: "Aysel Hüseynova",
    bio: {
      az: "Boyama və balayaj üzrə sertifikatlı master. Avropa məktəbinin məzunu.",
      ru: "Сертифицированный мастер по окрашиванию и балаяжу. Выпускница европейской школы.",
    },
    rating: 5.0,
    reviewsCount: 412,
    specialties: ["coloring", "styling"],
    priceRange: "high",
    serviceIds: ["s6", "s7", "s8", "s9", "s10"],
    workingHours: { start: "10:00", end: "20:00" },
    breaks: [{ start: "14:00", end: "15:00" }],
    city: { az: "Bakı", ru: "Баку" },
    kind: "salon",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 12,
    experienceYears: 9,
    district: { az: "Bakı, Yasamal", ru: "Баку, Ясамал" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/ayselh1/600/450",
      "https://picsum.photos/seed/ayselh2/600/450",
      "https://picsum.photos/seed/ayselh3/600/450",
      "https://picsum.photos/seed/ayselh4/600/450",
      "https://picsum.photos/seed/ayselh5/600/450",
    ],
  },
  {
    id: "u3",
    name: "Rəşad Quliyev",
    bio: {
      az: "Barber-shop sahibi. Saqqal forması və klassik briç ustası.",
      ru: "Владелец барбершопа. Мастер по моделированию бороды и классическим стрижкам.",
    },
    rating: 4.8,
    reviewsCount: 187,
    specialties: ["beard", "haircut"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s3", "s4", "s5"],
    workingHours: { start: "10:00", end: "21:00" },
    breaks: [{ start: "15:00", end: "16:00" }],
    city: { az: "Bakı", ru: "Баку" },
    kind: "barber",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 6,
    experienceYears: 12,
    district: { az: "Bakı, Sahil", ru: "Баку, Сахиль" },
  },
  {
    id: "u4",
    name: "Lalə Əliyeva",
    bio: {
      az: "Toy və xüsusi günlər üçün saç düzümü mütəxəssisi. Səbirli və diqqətli.",
      ru: "Специалист по причёскам для свадеб и особых случаев. Терпеливая и внимательная.",
    },
    rating: 4.7,
    reviewsCount: 156,
    specialties: ["styling", "coloring"],
    priceRange: "high",
    serviceIds: ["s6", "s8", "s9"],
    workingHours: { start: "09:00", end: "18:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: { az: "Gəncə", ru: "Гянджа" },
    kind: "makeup",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 18,
    experienceYears: 6,
    district: { az: "Gəncə, mərkəz", ru: "Гянджа, центр" },
  },
  {
    id: "u5",
    name: "Tural Bayramov",
    bio: {
      az: "Sürətli, sərfəli və keyfiyyətli xidmət. Uşaq kəsimlərində yaxşı.",
      ru: "Быстрое, доступное и качественное обслуживание. Хорош в детских стрижках.",
    },
    rating: 4.5,
    reviewsCount: 98,
    specialties: ["haircut", "beard"],
    priceRange: "low",
    serviceIds: ["s1", "s3", "s4"],
    workingHours: { start: "08:00", end: "17:00" },
    breaks: [{ start: "12:00", end: "13:00" }],
    city: { az: "Sumqayıt", ru: "Сумгаит" },
    kind: "barber",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 10,
    experienceYears: 4,
    district: { az: "Sumqayıt, 8-ci mikrorayon", ru: "Сумгаит, 8-й микрорайон" },
  },
  {
    id: "u6",
    name: "Nigar Rəhimova",
    bio: {
      az: "Keratin və düzləşdirmə prosedurları üzrə peşəkar. Yumşaq və təbii nəticə.",
      ru: "Профессионал по кератину и процедурам выпрямления. Мягкий и естественный результат.",
    },
    rating: 4.9,
    reviewsCount: 301,
    specialties: ["styling", "coloring"],
    priceRange: "high",
    serviceIds: ["s7", "s8", "s10"],
    workingHours: { start: "11:00", end: "20:00" },
    breaks: [{ start: "15:00", end: "16:00" }],
    city: { az: "Bakı", ru: "Баку" },
    kind: "salon",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 14,
    experienceYears: 11,
    district: { az: "Bakı, Nərimanov", ru: "Баку, Нариманов" },
    verified: true,
  },
  {
    id: "u7",
    name: "Cavid İsmayılov",
    bio: {
      az: "Müasir trendləri izləyən gənc barber. Fade və texturalı kəsimlərdə güclü.",
      ru: "Молодой барбер, следящий за современными трендами. Силён в фейдах и текстурных стрижках.",
    },
    rating: 4.6,
    reviewsCount: 142,
    specialties: ["haircut"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s3"],
    workingHours: { start: "10:00", end: "19:00" },
    breaks: [{ start: "14:00", end: "15:00" }],
    city: { az: "Bakı", ru: "Баку" },
    kind: "barber",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 9,
    experienceYears: 5,
    district: { az: "Bakı, Xətai", ru: "Баку, Хатаи" },
  },
  {
    id: "u8",
    name: "Səbinə Kərimova",
    bio: {
      az: "Boyama studiyasının baş ustası. Rəng nəzəriyyəsində dərin biliklər.",
      ru: "Главный мастер студии окрашивания. Глубокие знания в теории цвета.",
    },
    rating: 4.8,
    reviewsCount: 268,
    specialties: ["coloring", "styling"],
    priceRange: "medium",
    serviceIds: ["s6", "s7", "s8"],
    workingHours: { start: "09:00", end: "18:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: { az: "Gəncə", ru: "Гянджа" },
    kind: "makeup",
    tier: "beauty",
    priceUnit: { az: "vizit", ru: "визит" },
    responseMins: 15,
    experienceYears: 8,
    district: { az: "Gəncə, Heydər Əliyev pr.", ru: "Гянджа, пр. Гейдара Алиева" },
  },
  // Event-tier providers
  {
    id: "u9",
    name: "Aysel Kərimova",
    bio: {
      az: "Toy və lovestory çəkilişlərində ixtisaslaşmış fotoqraf. 7 il təcrübə.",
      ru: "Фотограф, специализирующийся на свадебных и lovestory-съёмках. 7 лет опыта.",
    },
    rating: 4.9,
    reviewsCount: 184,
    specialties: ["shoot"],
    priceRange: "high",
    serviceIds: ["s11", "s12", "s13"],
    workingHours: { start: "09:00", end: "20:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "photographer",
    tier: "event",
    priceUnit: { az: "saat", ru: "час" },
    responseMins: 11,
    experienceYears: 7,
    district: { az: "Bakı, Nəsimi", ru: "Баку, Насими" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/aysel1/600/450",
      "https://picsum.photos/seed/aysel2/600/450",
      "https://picsum.photos/seed/aysel3/600/450",
      "https://picsum.photos/seed/aysel4/600/450",
      "https://picsum.photos/seed/aysel5/600/450",
    ],
  },
  {
    id: "u10",
    name: "Rauf Vəliyev",
    bio: {
      az: "Toy aparıcısı. Azərbaycan və rus dillərində aparır. 8 il təcrübə.",
      ru: "Ведущий свадеб. Ведёт на азербайджанском и русском. 8 лет опыта.",
    },
    rating: 4.8,
    reviewsCount: 156,
    specialties: ["host"],
    priceRange: "high",
    serviceIds: ["s18"],
    workingHours: { start: "16:00", end: "23:30" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "host",
    tier: "event",
    priceUnit: { az: "axşam", ru: "вечер" },
    responseMins: 22,
    experienceYears: 8,
    district: { az: "Bakı, Nərimanov", ru: "Баку, Нариманов" },
    gallery: [
      "https://picsum.photos/seed/rauf1/600/450",
      "https://picsum.photos/seed/rauf2/600/450",
      "https://picsum.photos/seed/rauf3/600/450",
      "https://picsum.photos/seed/rauf4/600/450",
    ],
  },
  {
    id: "u11",
    name: "DJ Nihad",
    bio: {
      az: "Toy və korporativ tədbirlər üçün DJ. House, deep, milli mahnılar.",
      ru: "DJ для свадеб и корпоративов. House, deep, национальные миксы.",
    },
    rating: 4.9,
    reviewsCount: 221,
    specialties: ["djset"],
    priceRange: "medium",
    serviceIds: ["s14", "s15"],
    workingHours: { start: "18:00", end: "03:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "dj",
    tier: "event",
    priceUnit: { az: "set", ru: "сет" },
    responseMins: 7,
    experienceYears: 9,
    district: { az: "Bakı, Yasamal", ru: "Баку, Ясамал" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/djnihad1/600/450",
      "https://picsum.photos/seed/djnihad2/600/450",
      "https://picsum.photos/seed/djnihad3/600/450",
      "https://picsum.photos/seed/djnihad4/600/450",
    ],
  },
  {
    id: "u12",
    name: "Restoran Çinar",
    bio: {
      az: "Banket zalı. 250 qonağa qədər. Milli və Avropa mətbəxi.",
      ru: "Банкетный зал. До 250 гостей. Национальная и европейская кухня.",
    },
    rating: 4.7,
    reviewsCount: 312,
    specialties: ["banquet"],
    priceRange: "high",
    serviceIds: ["s16", "s17"],
    workingHours: { start: "12:00", end: "00:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "restaurant",
    tier: "event",
    priceUnit: { az: "şəxs", ru: "персона" },
    responseMins: 25,
    experienceYears: 12,
    district: { az: "Bakı, Sahil", ru: "Баку, Сахиль" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/cinar1/600/450",
      "https://picsum.photos/seed/cinar2/600/450",
      "https://picsum.photos/seed/cinar3/600/450",
      "https://picsum.photos/seed/cinar4/600/450",
      "https://picsum.photos/seed/cinar5/600/450",
    ],
  },
  {
    id: "u13",
    name: "Sənan Quliyev",
    bio: {
      az: "Event və ailə çəkilişləri. Reportaj fotoqrafı.",
      ru: "Event и семейные съёмки. Репортажный фотограф.",
    },
    rating: 4.6,
    reviewsCount: 98,
    specialties: ["shoot"],
    priceRange: "medium",
    serviceIds: ["s12", "s13"],
    workingHours: { start: "10:00", end: "21:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "photographer",
    tier: "event",
    priceUnit: { az: "saat", ru: "час" },
    responseMins: 13,
    experienceYears: 5,
    district: { az: "Bakı, Xətai", ru: "Баку, Хатаи" },
    gallery: [
      "https://picsum.photos/seed/senan1/600/450",
      "https://picsum.photos/seed/senan2/600/450",
      "https://picsum.photos/seed/senan3/600/450",
      "https://picsum.photos/seed/senan4/600/450",
    ],
  },
  {
    id: "u14",
    name: "DJ Aytac",
    bio: {
      az: "Private və korporativ tədbirlər. Deep, techno və retro setlər.",
      ru: "Private и корпоративные мероприятия. Deep, techno и retro-сеты.",
    },
    rating: 4.7,
    reviewsCount: 134,
    specialties: ["djset"],
    priceRange: "medium",
    serviceIds: ["s14", "s15"],
    workingHours: { start: "19:00", end: "04:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "dj",
    tier: "event",
    priceUnit: { az: "set", ru: "сет" },
    responseMins: 16,
    experienceYears: 6,
    district: { az: "Bakı, Nəsimi", ru: "Баку, Насими" },
    gallery: [
      "https://picsum.photos/seed/aytac1/600/450",
      "https://picsum.photos/seed/aytac2/600/450",
      "https://picsum.photos/seed/aytac3/600/450",
      "https://picsum.photos/seed/aytac4/600/450",
    ],
  },
  {
    id: "u15",
    name: "Restoran Şirvanşah",
    bio: {
      az: "Premium banket zalı. 400 qonağa qədər. VIP xidmət.",
      ru: "Премиум банкетный зал. До 400 гостей. VIP-обслуживание.",
    },
    rating: 4.9,
    reviewsCount: 489,
    specialties: ["banquet"],
    priceRange: "high",
    serviceIds: ["s16", "s17"],
    workingHours: { start: "12:00", end: "01:00" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "restaurant",
    tier: "event",
    priceUnit: { az: "şəxs", ru: "персона" },
    responseMins: 30,
    experienceYears: 18,
    district: { az: "Bakı, Nəsimi", ru: "Баку, Насими" },
    verified: true,
    gallery: [
      "https://picsum.photos/seed/sirvan1/600/450",
      "https://picsum.photos/seed/sirvan2/600/450",
      "https://picsum.photos/seed/sirvan3/600/450",
      "https://picsum.photos/seed/sirvan4/600/450",
      "https://picsum.photos/seed/sirvan5/600/450",
      "https://picsum.photos/seed/sirvan6/600/450",
    ],
  },
  {
    id: "u16",
    name: "Rauf Aslanov",
    bio: {
      az: "Toy və korporativ tədbirlərin aparıcısı. Yumoristik üslub.",
      ru: "Ведущий свадеб и корпоративов. Юмористичный стиль.",
    },
    rating: 4.7,
    reviewsCount: 117,
    specialties: ["host"],
    priceRange: "medium",
    serviceIds: ["s18"],
    workingHours: { start: "16:00", end: "23:30" },
    breaks: [],
    city: { az: "Bakı", ru: "Баку" },
    kind: "host",
    tier: "event",
    priceUnit: { az: "axşam", ru: "вечер" },
    responseMins: 19,
    experienceYears: 7,
    district: { az: "Bakı, Yasamal", ru: "Баку, Ясамал" },
    gallery: [
      "https://picsum.photos/seed/raufa1/600/450",
      "https://picsum.photos/seed/raufa2/600/450",
      "https://picsum.photos/seed/raufa3/600/450",
      "https://picsum.photos/seed/raufa4/600/450",
    ],
  },
];

export const PROVIDERS = STYLISTS;

export const APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    stylistId: "u1",
    clientName: "Orxan Hüseynov",
    serviceId: "s1",
    date: getDateISO(0),
    time: "10:30",
    status: "upcoming",
  },
  {
    id: "a2",
    stylistId: "u1",
    clientName: "Vüsal Əhmədov",
    serviceId: "s4",
    date: getDateISO(0),
    time: "15:00",
    status: "upcoming",
  },
  {
    id: "a3",
    stylistId: "u2",
    clientName: "Günel Səfərova",
    serviceId: "s7",
    date: getDateISO(1),
    time: "11:00",
    status: "upcoming",
  },
  {
    id: "a4",
    stylistId: "u3",
    clientName: "Kamran Qədimov",
    serviceId: "s2",
    date: getDateISO(2),
    time: "16:30",
    status: "upcoming",
  },
  {
    id: "a5",
    stylistId: "u9",
    clientName: "Aynur Mehdiyeva",
    serviceId: "s11",
    date: getDateISO(3),
    time: "09:30",
    status: "upcoming",
  },
  {
    id: "a6",
    stylistId: "u12",
    clientName: "Leyla Abbasova",
    serviceId: "s16",
    date: getDateISO(5),
    time: "18:00",
    status: "upcoming",
  },
  {
    id: "a7",
    stylistId: "u1",
    clientName: "Rəvan Nəbiyev",
    serviceId: "s2",
    date: getDateISO(-3),
    time: "11:00",
    status: "completed",
  },
  {
    id: "a8",
    stylistId: "u2",
    clientName: "Mələk Əliyeva",
    serviceId: "s8",
    date: getDateISO(-5),
    time: "14:00",
    status: "completed",
  },
  {
    id: "a9",
    stylistId: "u5",
    clientName: "Elçin Məhərrəmov",
    serviceId: "s1",
    date: getDateISO(-7),
    time: "10:00",
    status: "completed",
  },
  {
    id: "a10",
    stylistId: "u8",
    clientName: "Türkan Həsənova",
    serviceId: "s6",
    date: getDateISO(-2),
    time: "13:30",
    status: "completed",
  },
];

export const TENDERS: readonly Tender[] = [
  {
    id: "t1",
    tier: "event",
    kind: "photographer",
    title: {
      az: "Toy üçün fotoqraf lazımdır — 15 may, büdcə 2 000 ₼",
      ru: "Нужен фотограф на свадьбу — 15 мая, бюджет 2 000 ₼",
    },
    description: {
      az: "Mərasim saat 16:00, banket Şirvanşahda. Tam günlük çəkiliş + 80 emal olunmuş kadr. Second-shooter opsionaldır. İstilik və təbii rənglər istərdik.",
      ru: "Церемония в 16:00, банкет в «Şirvanşah». Полный день съёмки + 80 обработанных кадров. Second-shooter опционально. Хочется тёплую и естественную обработку.",
    },
    budgetMin: 1700,
    budgetMax: 2000,
    deadline: "2026-05-15",
    openedAt: "2026-05-02",
    tags: [
      { az: "Toy", ru: "Свадьба" },
      { az: "8 saat", ru: "8 часов" },
      { az: "Səfər", ru: "Выезд" },
      { az: "İstilik emalı", ru: "Тёплая обработка" },
    ],
    bidsCount: 3,
    bids: [
      {
        id: "t1b1",
        providerId: "u9",
        providerName: "Aysel Kərimova",
        price: 1800,
        note: {
          az: "15 maya hazıram. Second-shooter daxildir, 100 kadr.",
          ru: "Готова к 15 мая. Включён second-shooter, 100 кадров.",
        },
        badges: ["verified", "rating"],
        rating: 4.9,
      },
      {
        id: "t1b2",
        providerId: "u16",
        providerName: "Rauf Aslanov",
        price: 1950,
        note: {
          az: "8 saat + dron + 120 foto. Sabah görüşə hazıram.",
          ru: "8 часов + дрон + 120 фото. Готов встретиться завтра.",
        },
        badges: ["rating", "fastResponse"],
        rating: 4.7,
      },
      {
        id: "t1b3",
        providerId: "u13",
        providerName: "Sənan Quliyev",
        price: 2100,
        note: {
          az: "Tam gün, second-shooter, hədiyyə mini-albom.",
          ru: "Полный день, second-shooter, мини-альбом в подарок.",
        },
        badges: ["rating", "topEvent"],
        rating: 4.95,
      },
    ],
    authorName: "Aytən S.",
    district: { az: "Bakı, Sahil", ru: "Баку, Сахиль" },
  },
  {
    id: "t2",
    tier: "event",
    kind: "dj",
    title: {
      az: "Korporativ tədbir üçün DJ — 4 saatlıq set",
      ru: "DJ на корпоратив — 4-часовой сет",
    },
    description: {
      az: "Şirkət 5 illiyi. 80 nəfər. House və retro qarışıq. Aparatura yerdədir.",
      ru: "Юбилей компании 5 лет. 80 человек. House и ретро вперемешку. Аппаратура на месте.",
    },
    budgetMin: 600,
    budgetMax: 900,
    deadline: "2026-05-20",
    openedAt: "2026-05-02",
    tags: [
      { az: "Korporativ", ru: "Корпоратив" },
      { az: "4 saat", ru: "4 часа" },
      { az: "House · retro", ru: "House · ретро" },
    ],
    bidsCount: 2,
    bids: [
      {
        id: "t2b1",
        providerId: "u11",
        providerName: "DJ Nihad",
        price: 750,
        note: {
          az: "Hazıram. Mikrofon və işıq da gətirə bilərəm.",
          ru: "Готов. Могу привезти микрофон и свет.",
        },
        badges: ["verified", "rating"],
        rating: 4.9,
      },
      {
        id: "t2b2",
        providerId: "u14",
        providerName: "DJ Aytac",
        price: 680,
        note: {
          az: "Retro-set ixtisasım. 4 saat + bonus 30 dəq.",
          ru: "Ретро-сет — моя специализация. 4 часа + бонус 30 мин.",
        },
        badges: ["rating", "fastResponse"],
        rating: 4.7,
      },
    ],
    authorName: "Murad H.",
    district: { az: "Bakı, Yasamal", ru: "Баку, Ясамал" },
  },
  {
    id: "t3",
    tier: "event",
    kind: "restaurant",
    title: {
      az: "80 nəfərlik ad günü üçün restoran",
      ru: "Ресторан для дня рождения на 80 гостей",
    },
    description: {
      az: "30 may, şənbə axşamı. Milli və Avropa mətbəxinin qarışığı. Səhnə və DJ üçün yer olsun.",
      ru: "30 мая, субботний вечер. Микс национальной и европейской кухни. Желательно сцена и место под DJ.",
    },
    budgetMin: 2500,
    budgetMax: 3500,
    deadline: "2026-05-30",
    openedAt: "2026-05-01",
    tags: [
      { az: "Ad günü", ru: "День рождения" },
      { az: "80 qonaq", ru: "80 гостей" },
      { az: "Səhnə", ru: "Сцена" },
    ],
    bidsCount: 1,
    bids: [
      {
        id: "t3b1",
        providerId: "u15",
        providerName: "Restoran Şirvanşah",
        price: 3200,
        note: {
          az: "30 may boşdur. VIP zal + səhnə + işıq daxildir.",
          ru: "30 мая свободно. VIP-зал + сцена + свет включены.",
        },
        badges: ["verified", "topEvent", "rating"],
        rating: 4.9,
      },
    ],
    authorName: "Leyla M.",
    district: { az: "Bakı, Nəsimi", ru: "Баку, Насими" },
  },
  {
    id: "t4",
    tier: "beauty",
    kind: "barber",
    title: {
      az: "Evdə barber — təcili",
      ru: "Барбер на дом — срочно",
    },
    description: {
      az: "Sabah səhər saç + saqqal. Yasamal, Ə. Abbaszadə. Öz aparatım yoxdur.",
      ru: "Завтра утром стрижка + борода. Ясамал, ул. Абасзаде. Своего инструмента нет.",
    },
    budgetMin: 30,
    budgetMax: 50,
    deadline: "2026-05-03",
    openedAt: "2026-05-02",
    tags: [
      { az: "Səfər", ru: "Выезд" },
      { az: "Saç + saqqal", ru: "Стрижка + борода" },
      { az: "Təcili", ru: "Срочно" },
    ],
    bidsCount: 4,
    bids: [
      {
        id: "t4b1",
        providerId: "u1",
        providerName: "Elvin Məmmədov",
        price: 45,
        note: {
          az: "Sabah 09:00-da gələ bilərəm.",
          ru: "Могу подъехать завтра к 09:00.",
        },
        badges: ["verified", "rating"],
        rating: 4.9,
      },
      {
        id: "t4b2",
        providerId: "u3",
        providerName: "Rəşad Quliyev",
        price: 40,
        note: {
          az: "Sabah 10:30 boşdur. Tam dəstlə gələcəyəm.",
          ru: "Завтра 10:30 свободно. Приеду с полным набором.",
        },
        badges: ["rating", "fastResponse"],
        rating: 4.8,
      },
      {
        id: "t4b3",
        providerId: "u7",
        providerName: "Cavid İsmayılov",
        price: 35,
        note: {
          az: "Fade və saqqal — mənim profilim. Sabah 11:00.",
          ru: "Фейд и борода — мой профиль. Завтра 11:00.",
        },
        badges: ["rating"],
        rating: 4.6,
      },
      {
        id: "t4b4",
        providerId: "u5",
        providerName: "Tural Bayramov",
        price: 30,
        note: {
          az: "Səhər 08:30-da hazıram. Sərfəli qiymət.",
          ru: "Готов к 08:30 утра. Бюджетная цена.",
        },
        badges: ["fastResponse"],
        rating: 4.5,
      },
    ],
    authorName: "Ələkbər N.",
    district: { az: "Bakı, Yasamal", ru: "Баку, Ясамал" },
  },
  {
    id: "t5",
    tier: "beauty",
    kind: "makeup",
    title: {
      az: "Toy səhəri üçün vizajist",
      ru: "Визажист на свадебное утро",
    },
    description: {
      az: "Gəlin + 2 qonaq. 18 may, səhər saat 08:00-dan. Təbii makiyaj.",
      ru: "Невеста + 2 гостьи. 18 мая, начало в 08:00. Натуральный макияж.",
    },
    budgetMin: 200,
    budgetMax: 400,
    deadline: "2026-05-18",
    openedAt: "2026-05-02",
    tags: [
      { az: "Toy", ru: "Свадьба" },
      { az: "Gəlin makiyajı", ru: "Свадебный макияж" },
      { az: "Səfər", ru: "Выезд" },
    ],
    bidsCount: 2,
    bids: [
      {
        id: "t5b1",
        providerId: "u4",
        providerName: "Lalə Əliyeva",
        price: 320,
        note: {
          az: "Gəlin + 2 qonaq, 3 saat. Saç düzümü də əlavə oluna bilər.",
          ru: "Невеста + 2 гостьи, 3 часа. Могу добавить причёску.",
        },
        badges: ["rating", "fastResponse"],
        rating: 4.7,
      },
      {
        id: "t5b2",
        providerId: "u8",
        providerName: "Səbinə Kərimova",
        price: 280,
        note: {
          az: "Təbii və davamlı makiyaj — mənim profilim.",
          ru: "Натуральный и стойкий макияж — мой профиль.",
        },
        badges: ["verified", "rating"],
        rating: 4.8,
      },
    ],
    authorName: "Nigar A.",
    district: { az: "Bakı, Nərimanov", ru: "Баку, Нариманов" },
  },
] as const;
