import type { Appointment, Service, Stylist } from "./types";
import { getDateISO } from "./utils";

export const SERVICES: Service[] = [
  {
    id: "s1",
    name: "Klassik saç kəsimi",
    category: "haircut",
    durationMin: 45,
    price: 25,
  },
  {
    id: "s2",
    name: "Modern fade kəsim",
    category: "haircut",
    durationMin: 60,
    price: 35,
  },
  {
    id: "s3",
    name: "Uşaq saç kəsimi",
    category: "haircut",
    durationMin: 30,
    price: 18,
  },
  {
    id: "s4",
    name: "Saqqal düzəltmə",
    category: "beard",
    durationMin: 25,
    price: 15,
  },
  {
    id: "s5",
    name: "Premium saqqal forması",
    category: "beard",
    durationMin: 40,
    price: 28,
  },
  {
    id: "s6",
    name: "Tam saç boyama",
    category: "coloring",
    durationMin: 120,
    price: 90,
  },
  {
    id: "s7",
    name: "Melir və balayaj",
    category: "coloring",
    durationMin: 150,
    price: 120,
  },
  {
    id: "s8",
    name: "Fön və stayl",
    category: "styling",
    durationMin: 45,
    price: 30,
  },
  {
    id: "s9",
    name: "Toy saç düzümü",
    category: "styling",
    durationMin: 90,
    price: 75,
  },
  {
    id: "s10",
    name: "Keratin düzləşdirmə",
    category: "styling",
    durationMin: 180,
    price: 180,
  },
];

export const STYLISTS: Stylist[] = [
  {
    id: "u1",
    name: "Elvin Məmmədov",
    avatar: "https://i.pravatar.cc/300?img=12",
    bio: "10 ildən artıq təcrübəli kişi ustası. Klassik və müasir kəsimlərdə ixtisaslaşıb.",
    rating: 4.9,
    reviewsCount: 234,
    specialties: ["haircut", "beard"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s4", "s5"],
    workingHours: { start: "09:00", end: "19:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: "Bakı",
  },
  {
    id: "u2",
    name: "Aysel Hüseynova",
    avatar: "https://i.pravatar.cc/300?img=47",
    bio: "Boyama və balayaj üzrə sertifikatlı master. Avropa məktəbinin məzunu.",
    rating: 5.0,
    reviewsCount: 412,
    specialties: ["coloring", "styling"],
    priceRange: "high",
    serviceIds: ["s6", "s7", "s8", "s9", "s10"],
    workingHours: { start: "10:00", end: "20:00" },
    breaks: [{ start: "14:00", end: "15:00" }],
    city: "Bakı",
  },
  {
    id: "u3",
    name: "Rəşad Quliyev",
    avatar: "https://i.pravatar.cc/300?img=33",
    bio: "Barber-shop sahibi. Saqqal forması və klassik briç ustası.",
    rating: 4.8,
    reviewsCount: 187,
    specialties: ["beard", "haircut"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s3", "s4", "s5"],
    workingHours: { start: "10:00", end: "21:00" },
    breaks: [{ start: "15:00", end: "16:00" }],
    city: "Bakı",
  },
  {
    id: "u4",
    name: "Lalə Əliyeva",
    avatar: "https://i.pravatar.cc/300?img=49",
    bio: "Toy və xüsusi günlər üçün saç düzümü mütəxəssisi. Səbirli və diqqətli.",
    rating: 4.7,
    reviewsCount: 156,
    specialties: ["styling", "coloring"],
    priceRange: "high",
    serviceIds: ["s6", "s8", "s9"],
    workingHours: { start: "09:00", end: "18:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: "Gəncə",
  },
  {
    id: "u5",
    name: "Tural Bayramov",
    avatar: "https://i.pravatar.cc/300?img=15",
    bio: "Sürətli, sərfəli və keyfiyyətli xidmət. Uşaq kəsimlərində yaxşı.",
    rating: 4.5,
    reviewsCount: 98,
    specialties: ["haircut", "beard"],
    priceRange: "low",
    serviceIds: ["s1", "s3", "s4"],
    workingHours: { start: "08:00", end: "17:00" },
    breaks: [{ start: "12:00", end: "13:00" }],
    city: "Sumqayıt",
  },
  {
    id: "u6",
    name: "Nigar Rəhimova",
    avatar: "https://i.pravatar.cc/300?img=44",
    bio: "Keratin və düzləşdirmə prosedurları üzrə peşəkar. Yumşaq və təbii nəticə.",
    rating: 4.9,
    reviewsCount: 301,
    specialties: ["styling", "coloring"],
    priceRange: "high",
    serviceIds: ["s7", "s8", "s10"],
    workingHours: { start: "11:00", end: "20:00" },
    breaks: [{ start: "15:00", end: "16:00" }],
    city: "Bakı",
  },
  {
    id: "u7",
    name: "Cavid İsmayılov",
    avatar: "https://i.pravatar.cc/300?img=68",
    bio: "Müasir trendləri izləyən gənc barber. Fade və texturalı kəsimlərdə güclü.",
    rating: 4.6,
    reviewsCount: 142,
    specialties: ["haircut"],
    priceRange: "medium",
    serviceIds: ["s1", "s2", "s3"],
    workingHours: { start: "10:00", end: "19:00" },
    breaks: [{ start: "14:00", end: "15:00" }],
    city: "Bakı",
  },
  {
    id: "u8",
    name: "Səbinə Kərimova",
    avatar: "https://i.pravatar.cc/300?img=23",
    bio: "Boyama studiyasının baş ustası. Rəng nəzəriyyəsində dərin biliklər.",
    rating: 4.8,
    reviewsCount: 268,
    specialties: ["coloring", "styling"],
    priceRange: "medium",
    serviceIds: ["s6", "s7", "s8"],
    workingHours: { start: "09:00", end: "18:00" },
    breaks: [{ start: "13:00", end: "14:00" }],
    city: "Gəncə",
  },
];

export const APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    stylistId: "u1",
    clientName: "Orxan Hüseynov",
    serviceId: "s1",
    date: getDateISO(0),
    time: "10:30",
    status: "upcoming",
  },
  {
    id: "a2",
    stylistId: "u1",
    clientName: "Vüsal Əhmədov",
    serviceId: "s4",
    date: getDateISO(0),
    time: "15:00",
    status: "upcoming",
  },
  {
    id: "a3",
    stylistId: "u2",
    clientName: "Günel Səfərova",
    serviceId: "s7",
    date: getDateISO(1),
    time: "11:00",
    status: "upcoming",
  },
  {
    id: "a4",
    stylistId: "u3",
    clientName: "Kamran Qədimov",
    serviceId: "s2",
    date: getDateISO(2),
    time: "16:30",
    status: "upcoming",
  },
  {
    id: "a5",
    stylistId: "u4",
    clientName: "Aynur Mehdiyeva",
    serviceId: "s9",
    date: getDateISO(3),
    time: "09:30",
    status: "upcoming",
  },
  {
    id: "a6",
    stylistId: "u6",
    clientName: "Leyla Abbasova",
    serviceId: "s10",
    date: getDateISO(5),
    time: "12:00",
    status: "upcoming",
  },
  {
    id: "a7",
    stylistId: "u1",
    clientName: "Rəvan Nəbiyev",
    serviceId: "s2",
    date: getDateISO(-3),
    time: "11:00",
    status: "completed",
  },
  {
    id: "a8",
    stylistId: "u2",
    clientName: "Mələk Əliyeva",
    serviceId: "s8",
    date: getDateISO(-5),
    time: "14:00",
    status: "completed",
  },
  {
    id: "a9",
    stylistId: "u5",
    clientName: "Elçin Məhərrəmov",
    serviceId: "s1",
    date: getDateISO(-7),
    time: "10:00",
    status: "completed",
  },
  {
    id: "a10",
    stylistId: "u8",
    clientName: "Türkan Həsənova",
    serviceId: "s6",
    date: getDateISO(-2),
    time: "13:30",
    status: "completed",
  },
];
