/**
 * Reads lib/mock-data.ts and emits supabase/seed.sql.
 * Run: npx tsx scripts/generate-supabase-seed.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  APPOINTMENTS,
  PROVIDERS,
  SERVICES,
  TENDERS,
} from "../lib/mock-data";

function sqlText(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value)) {
    if (value.length === 0) return "'{}'";
    if (value.every((v) => typeof v === "string")) {
      const inner = value
        .map((v) => `"${(v as string).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`)
        .join(",");
      return `'{${inner}}'`;
    }
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  if (typeof value === "object") {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  // string
  return `'${String(value).replace(/'/g, "''")}'`;
}

function row(values: unknown[]): string {
  return `(${values.map(sqlText).join(", ")})`;
}

const lines: string[] = [
  "-- Auto-generated by scripts/generate-supabase-seed.ts",
  "-- Do not edit by hand.",
  "",
  "begin;",
  "",
  "-- Wipe existing rows so re-running this seed is idempotent.",
  "truncate table tender_bids, tenders, reviews, appointments, provider_edits, providers, services restart identity cascade;",
  "",
];

// Services
lines.push("-- services -----------------------------------------------------------");
lines.push(
  "insert into services (id, name, category, duration_min, price) values",
);
lines.push(
  SERVICES.map((s) =>
    row([s.id, s.name, s.category, s.durationMin, s.price]),
  ).join(",\n") + ";",
);
lines.push("");

// Providers
lines.push("-- providers ----------------------------------------------------------");
lines.push(
  `insert into providers (
    id, name, bio, rating, reviews_count, specialties, price_range,
    service_ids, working_hours, breaks, city, kind, tier,
    price_unit, response_mins, experience_years, district, gallery, avatar, verified
  ) values`,
);
lines.push(
  PROVIDERS.map((p) =>
    row([
      p.id,
      p.name,
      p.bio,
      p.rating,
      p.reviewsCount,
      p.specialties,
      p.priceRange,
      p.serviceIds,
      p.workingHours,
      p.breaks,
      p.city,
      p.kind,
      p.tier,
      p.priceUnit ?? null,
      p.responseMins ?? null,
      p.experienceYears ?? null,
      p.district ?? null,
      p.gallery ?? [],
      p.avatar ?? null,
      p.verified ?? false,
    ]),
  ).join(",\n") + ";",
);
lines.push("");

// Appointments
lines.push("-- appointments -------------------------------------------------------");
lines.push(
  'insert into appointments (id, stylist_id, client_name, service_id, date, "time", status) values',
);
lines.push(
  APPOINTMENTS.map((a) =>
    row([a.id, a.stylistId, a.clientName, a.serviceId, a.date, a.time, a.status]),
  ).join(",\n") + ";",
);
lines.push("");

// Tenders
lines.push("-- tenders -----------------------------------------------------------");
lines.push(
  `insert into tenders (
    id, tier, kind, title, description, budget_min, budget_max,
    deadline, opened_at, tags, author_name, district
  ) values`,
);
lines.push(
  TENDERS.map((t) =>
    row([
      t.id,
      t.tier,
      t.kind,
      t.title,
      t.description,
      t.budgetMin,
      t.budgetMax,
      t.deadline,
      t.openedAt,
      t.tags,
      t.authorName,
      t.district,
    ]),
  ).join(",\n") + ";",
);
lines.push("");

// Tender bids
lines.push("-- tender_bids -------------------------------------------------------");
const bidRows: string[] = [];
for (const t of TENDERS) {
  for (const b of t.bids) {
    bidRows.push(
      row([
        b.id,
        t.id,
        b.providerId,
        b.providerName,
        b.price,
        b.note,
        b.badges,
        b.rating ?? null,
      ]),
    );
  }
}
if (bidRows.length > 0) {
  lines.push(
    `insert into tender_bids (id, tender_id, provider_id, provider_name, price, note, badges, rating) values`,
  );
  lines.push(bidRows.join(",\n") + ";");
}
lines.push("");

lines.push("commit;");
lines.push("");

// Keep the timestamp stable so re-running this script overwrites the same
// file. If you ever bump the schema, update both files in lockstep.
const out = resolve(
  process.cwd(),
  "supabase/migrations/20260510190001_seed.sql",
);
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${lines.length} lines)`);
